INSERT INTO user(id,username,password,role) VALUES(15,'kiran','5f4dcc3b5aa765d61d8327deb882cf99','manager');
INSERT INTO user(id,username,password,role) VALUES(16,'harsha','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(17,'lingraj','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(18,'seeta','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(19,'tambe','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(30,'sujata','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(31,'senthil','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(32,'ravi','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(33,'sagar','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(34,'srinivas','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(35,'anuradha','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(36,'bipin','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(37,'panse','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(38,'demo','fe01ce2a7fbac8fafaed7c982a04e229','user');
INSERT INTO area(areaId,name,landmark,pincode) VALUES(13,'Barshi Urban','power station','413401');
INSERT INTO user(id,username,password,role) VALUES(21,'joshi','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO user(id,username,password,role) VALUES(22,'rahul','5f4dcc3b5aa765d61d8327deb882cf99','user');
INSERT INTO house(houseId,areaId) VALUES(3813001,13);
INSERT INTO household(householdId,houseId,areaId) VALUES(381300101,3813001,13);
INSERT INTO member(memberId,householdId,name,age_value,age_unit,gender) VALUES(38130010101,381300101,'maleMember','50','Years','Male');
INSERT INTO member(memberId,householdId,name,age_value,age_unit,gender) VALUES(38130010102,381300101,'femaleMember','40','Years','Female');
INSERT INTO district(state,name) VALUES(34,'Nicobars');
INSERT INTO district(state,name) VALUES(34,'North & middle Andamans');
INSERT INTO district(state,name) VALUES(34,'South Andamans');
INSERT INTO district(state,name) VALUES(4,'Adilabad');
INSERT INTO district(state,name) VALUES(4,'Anantapur');
INSERT INTO district(state,name) VALUES(4,'Chittoor');
INSERT INTO district(state,name) VALUES(4,'Cuddapah');
INSERT INTO district(state,name) VALUES(4,'East Godavari');
INSERT INTO district(state,name) VALUES(4,'Guntur');
INSERT INTO district(state,name) VALUES(4,'Hyderabad');
INSERT INTO district(state,name) VALUES(4,'Karimnagar');
INSERT INTO district(state,name) VALUES(4,'Khammam');
INSERT INTO district(state,name) VALUES(4,'Krishna');
INSERT INTO district(state,name) VALUES(4,'Kurnool');
INSERT INTO district(state,name) VALUES(4,'Mahbubnagar');
INSERT INTO district(state,name) VALUES(4,'Medak');
INSERT INTO district(state,name) VALUES(4,'Nalgonda');
INSERT INTO district(state,name) VALUES(4,'Nellore');
INSERT INTO district(state,name) VALUES(4,'Nizamabad');
INSERT INTO district(state,name) VALUES(4,'Prakasam');
INSERT INTO district(state,name) VALUES(4,'Rangareddi');
INSERT INTO district(state,name) VALUES(4,'Srikakulam');
INSERT INTO district(state,name) VALUES(4,'Visakhapatnam');
INSERT INTO district(state,name) VALUES(4,'Vizianagaram');
INSERT INTO district(state,name) VALUES(4,'Warangal');
INSERT INTO district(state,name) VALUES(4,'West Godavari');
INSERT INTO district(state,name) VALUES(17,'Anjaw');
INSERT INTO district(state,name) VALUES(17,'Changlang');
INSERT INTO district(state,name) VALUES(17,'Dibang Valley');
INSERT INTO district(state,name) VALUES(17,'East Kameng');
INSERT INTO district(state,name) VALUES(17,'East Siang');
INSERT INTO district(state,name) VALUES(17,'Kurung Kumey');
INSERT INTO district(state,name) VALUES(17,'Lohit');
INSERT INTO district(state,name) VALUES(17,'Lower Dibang Valley');
INSERT INTO district(state,name) VALUES(17,'Lower Subansiri');
INSERT INTO district(state,name) VALUES(17,'Papum Pare');
INSERT INTO district(state,name) VALUES(17,'Tawang');
INSERT INTO district(state,name) VALUES(17,'Tirap');
INSERT INTO district(state,name) VALUES(17,'Upper Siang');
INSERT INTO district(state,name) VALUES(17,'Upper Subansiri');
INSERT INTO district(state,name) VALUES(17,'West Kameng');
INSERT INTO district(state,name) VALUES(17,'West Siang');
INSERT INTO district(state,name) VALUES(18,'Baksa');
INSERT INTO district(state,name) VALUES(18,'Barpeta');
INSERT INTO district(state,name) VALUES(18,'Bongaigaon');
INSERT INTO district(state,name) VALUES(18,'Cachar');
INSERT INTO district(state,name) VALUES(18,'Cachar');
INSERT INTO district(state,name) VALUES(18,'Chirang');
INSERT INTO district(state,name) VALUES(18,'Darrang');
INSERT INTO district(state,name) VALUES(18,'Dhemaji');
INSERT INTO district(state,name) VALUES(18,'Dhubri');
INSERT INTO district(state,name) VALUES(18,'Dibrugarh');
INSERT INTO district(state,name) VALUES(18,'Goalpara');
INSERT INTO district(state,name) VALUES(18,'Golaghat');
INSERT INTO district(state,name) VALUES(18,'Hailakandi');
INSERT INTO district(state,name) VALUES(18,'Jorhat');
INSERT INTO district(state,name) VALUES(18,'Kamrup');
INSERT INTO district(state,name) VALUES(18,'Kamrup Metropolitan');
INSERT INTO district(state,name) VALUES(18,'Karbi Anglong');
INSERT INTO district(state,name) VALUES(18,'Karimganj');
INSERT INTO district(state,name) VALUES(18,'Kokrajhar');
INSERT INTO district(state,name) VALUES(18,'Lakhimpur');
INSERT INTO district(state,name) VALUES(18,'Marigaon');
INSERT INTO district(state,name) VALUES(18,'Nagaon');
INSERT INTO district(state,name) VALUES(18,'Nalbari');
INSERT INTO district(state,name) VALUES(18,'Sibsagar');
INSERT INTO district(state,name) VALUES(18,'Sonitpur');
INSERT INTO district(state,name) VALUES(18,'Tinsukia');
INSERT INTO district(state,name) VALUES(18,'Udalgiri');
INSERT INTO district(state,name) VALUES(9,'Araria');
INSERT INTO district(state,name) VALUES(9,'Arwal');
INSERT INTO district(state,name) VALUES(9,'Aurangabad');
INSERT INTO district(state,name) VALUES(9,'Banka');
INSERT INTO district(state,name) VALUES(9,'Begusarai');
INSERT INTO district(state,name) VALUES(9,'Bhagalpur');
INSERT INTO district(state,name) VALUES(9,'Bhojpur');
INSERT INTO district(state,name) VALUES(9,'Buxar');
INSERT INTO district(state,name) VALUES(9,'Darbhanga');
INSERT INTO district(state,name) VALUES(9,'Gaya');
INSERT INTO district(state,name) VALUES(9,'Gopalganj');
INSERT INTO district(state,name) VALUES(9,'Jamui');
INSERT INTO district(state,name) VALUES(9,'Jehanabad');
INSERT INTO district(state,name) VALUES(9,'Kaimur (Bhabua)');
INSERT INTO district(state,name) VALUES(9,'Katihar');
INSERT INTO district(state,name) VALUES(9,'Khagaria');
INSERT INTO district(state,name) VALUES(9,'Kishanganj');
INSERT INTO district(state,name) VALUES(9,'Lakhisarai');
INSERT INTO district(state,name) VALUES(9,'Madhepura');
INSERT INTO district(state,name) VALUES(9,'Madhubani');
INSERT INTO district(state,name) VALUES(9,'Munger');
INSERT INTO district(state,name) VALUES(9,'Muzaffarpur');
INSERT INTO district(state,name) VALUES(9,'Nalanda');
INSERT INTO district(state,name) VALUES(9,'Nawada');
INSERT INTO district(state,name) VALUES(9,'Pashchim Champaran');
INSERT INTO district(state,name) VALUES(9,'Patna');
INSERT INTO district(state,name) VALUES(9,'Purba Champaran');
INSERT INTO district(state,name) VALUES(9,'Purnia');
INSERT INTO district(state,name) VALUES(9,'Rohtas');
INSERT INTO district(state,name) VALUES(9,'Saharsa');
INSERT INTO district(state,name) VALUES(9,'Samastipur');
INSERT INTO district(state,name) VALUES(9,'Saran');
INSERT INTO district(state,name) VALUES(9,'Sheikhpura');
INSERT INTO district(state,name) VALUES(9,'Sheohar');
INSERT INTO district(state,name) VALUES(9,'Sitamarhi');
INSERT INTO district(state,name) VALUES(9,'Siwan');
INSERT INTO district(state,name) VALUES(9,'Supaul');
INSERT INTO district(state,name) VALUES(9,'Vaishali');
INSERT INTO district(state,name) VALUES(29,'Chandigarh');
INSERT INTO district(state,name) VALUES(19,'Baster');
INSERT INTO district(state,name) VALUES(19,'Bijapur');
INSERT INTO district(state,name) VALUES(19,'Bilaspur');
INSERT INTO district(state,name) VALUES(19,'Dantewada');
INSERT INTO district(state,name) VALUES(19,'Dhamtari');
INSERT INTO district(state,name) VALUES(19,'Durg');
INSERT INTO district(state,name) VALUES(19,'Janjgir - Champa');
INSERT INTO district(state,name) VALUES(19,'Jashpur');
INSERT INTO district(state,name) VALUES(19,'Kanker');
INSERT INTO district(state,name) VALUES(19,'Kawardha');
INSERT INTO district(state,name) VALUES(19,'Korba');
INSERT INTO district(state,name) VALUES(19,'Koriya');
INSERT INTO district(state,name) VALUES(19,'Mahasamund');
INSERT INTO district(state,name) VALUES(19,'Narayanpur');
INSERT INTO district(state,name) VALUES(19,'Raigarh');
INSERT INTO district(state,name) VALUES(19,'Raipur');
INSERT INTO district(state,name) VALUES(19,'Rajnandgaon');
INSERT INTO district(state,name) VALUES(19,'Surguja');
INSERT INTO district(state,name) VALUES(30,'Dadra & Nagar Haveli');
INSERT INTO district(state,name) VALUES(31,'Daman');
INSERT INTO district(state,name) VALUES(31,'Diu');
INSERT INTO district(state,name) VALUES(28,'Central District');
INSERT INTO district(state,name) VALUES(28,'East District');
INSERT INTO district(state,name) VALUES(28,'New Delhi');
INSERT INTO district(state,name) VALUES(28,'North District');
INSERT INTO district(state,name) VALUES(28,'North East District');
INSERT INTO district(state,name) VALUES(28,'North West District');
INSERT INTO district(state,name) VALUES(28,'South');
INSERT INTO district(state,name) VALUES(28,'South West');
INSERT INTO district(state,name) VALUES(28,'West District');
INSERT INTO district(state,name) VALUES(32,'North Goa');
INSERT INTO district(state,name) VALUES(32,'South Goa');
INSERT INTO district(state,name) VALUES(5,'Ahmedabad');
INSERT INTO district(state,name) VALUES(5,'Amreli');
INSERT INTO district(state,name) VALUES(5,'Anand');
INSERT INTO district(state,name) VALUES(5,'Banas Kantha');
INSERT INTO district(state,name) VALUES(5,'Bharuch');
INSERT INTO district(state,name) VALUES(5,'Bhavnagar');
INSERT INTO district(state,name) VALUES(5,'Dohad');
INSERT INTO district(state,name) VALUES(5,'Gandhinagar');
INSERT INTO district(state,name) VALUES(5,'Jamnagar');
INSERT INTO district(state,name) VALUES(5,'Junagadh');
INSERT INTO district(state,name) VALUES(5,'Kheda');
INSERT INTO district(state,name) VALUES(5,'Kutch');
INSERT INTO district(state,name) VALUES(5,'Mahesana');
INSERT INTO district(state,name) VALUES(5,'Narmada');
INSERT INTO district(state,name) VALUES(5,'Navsari');
INSERT INTO district(state,name) VALUES(5,'Panch Mahal');
INSERT INTO district(state,name) VALUES(5,'Patan');
INSERT INTO district(state,name) VALUES(5,'Porbandar');
INSERT INTO district(state,name) VALUES(5,'Rajkot');
INSERT INTO district(state,name) VALUES(5,'Sabar Kantha');
INSERT INTO district(state,name) VALUES(5,'Surat');
INSERT INTO district(state,name) VALUES(5,'Surendranagar');
INSERT INTO district(state,name) VALUES(5,'Tapi');
INSERT INTO district(state,name) VALUES(5,'The Dangs');
INSERT INTO district(state,name) VALUES(5,'Vadodara');
INSERT INTO district(state,name) VALUES(5,'Valsad');
INSERT INTO district(state,name) VALUES(22,'Ambala');
INSERT INTO district(state,name) VALUES(22,'Bhiwani');
INSERT INTO district(state,name) VALUES(22,'Faridabad');
INSERT INTO district(state,name) VALUES(22,'Fatehabad');
INSERT INTO district(state,name) VALUES(22,'Gurgaon');
INSERT INTO district(state,name) VALUES(22,'Hisar');
INSERT INTO district(state,name) VALUES(22,'Jamuna nagar');
INSERT INTO district(state,name) VALUES(22,'Jhajjar');
INSERT INTO district(state,name) VALUES(22,'Jind');
INSERT INTO district(state,name) VALUES(22,'Kaithal');
INSERT INTO district(state,name) VALUES(22,'Karnal');
INSERT INTO district(state,name) VALUES(22,'Kurukshetra');
INSERT INTO district(state,name) VALUES(22,'Mahendragarh');
INSERT INTO district(state,name) VALUES(22,'Mewat');
INSERT INTO district(state,name) VALUES(22,'palwal');
INSERT INTO district(state,name) VALUES(22,'Panchkula');
INSERT INTO district(state,name) VALUES(22,'Panipat');
INSERT INTO district(state,name) VALUES(22,'Rewari');
INSERT INTO district(state,name) VALUES(22,'Rohtak');
INSERT INTO district(state,name) VALUES(22,'Sirsa');
INSERT INTO district(state,name) VALUES(22,'Sonipat');
INSERT INTO district(state,name) VALUES(23,'Bilaspur');
INSERT INTO district(state,name) VALUES(23,'Chamba');
INSERT INTO district(state,name) VALUES(23,'Hamirpur');
INSERT INTO district(state,name) VALUES(23,'Kangra');
INSERT INTO district(state,name) VALUES(23,'Kinnaur');
INSERT INTO district(state,name) VALUES(23,'Kullu');
INSERT INTO district(state,name) VALUES(23,'Lahul & Spiti');
INSERT INTO district(state,name) VALUES(23,'Mandi');
INSERT INTO district(state,name) VALUES(23,'Shimla');
INSERT INTO district(state,name) VALUES(23,'Sirmaur');
INSERT INTO district(state,name) VALUES(23,'Solan');
INSERT INTO district(state,name) VALUES(23,'Una');
INSERT INTO district(state,name) VALUES(24,'Anantnag');
INSERT INTO district(state,name) VALUES(24,'Badgam');
INSERT INTO district(state,name) VALUES(24,'Bandipora');
INSERT INTO district(state,name) VALUES(24,'Baramula');
INSERT INTO district(state,name) VALUES(24,'Doda');
INSERT INTO district(state,name) VALUES(24,'Ganderbal');
INSERT INTO district(state,name) VALUES(24,'Jammu');
INSERT INTO district(state,name) VALUES(24,'Kargil');
INSERT INTO district(state,name) VALUES(24,'Kathua');
INSERT INTO district(state,name) VALUES(24,'Kishtwar');
INSERT INTO district(state,name) VALUES(24,'Kulgam');
INSERT INTO district(state,name) VALUES(24,'Kupwara');
INSERT INTO district(state,name) VALUES(24,'Leh (Ladakh)');
INSERT INTO district(state,name) VALUES(24,'Pulwama');
INSERT INTO district(state,name) VALUES(24,'Punch');
INSERT INTO district(state,name) VALUES(24,'Rajauri');
INSERT INTO district(state,name) VALUES(24,'Ramban');
INSERT INTO district(state,name) VALUES(24,'Reasi');
INSERT INTO district(state,name) VALUES(24,'Samba');
INSERT INTO district(state,name) VALUES(24,'Shupiyan');
INSERT INTO district(state,name) VALUES(24,'Srinagar');
INSERT INTO district(state,name) VALUES(24,'Udhampur');
INSERT INTO district(state,name) VALUES(12,'Bokaro');
INSERT INTO district(state,name) VALUES(12,'Chatra');
INSERT INTO district(state,name) VALUES(12,'Deoghar');
INSERT INTO district(state,name) VALUES(12,'Dhanbad');
INSERT INTO district(state,name) VALUES(12,'Dumka');
INSERT INTO district(state,name) VALUES(12,'Garhwa');
INSERT INTO district(state,name) VALUES(12,'Giridih');
INSERT INTO district(state,name) VALUES(12,'Godda');
INSERT INTO district(state,name) VALUES(12,'Gumla');
INSERT INTO district(state,name) VALUES(12,'Hazaribagh');
INSERT INTO district(state,name) VALUES(12,'Jamtara');
INSERT INTO district(state,name) VALUES(12,'Khunti');
INSERT INTO district(state,name) VALUES(12,'Kodarma');
INSERT INTO district(state,name) VALUES(12,'Latehar');
INSERT INTO district(state,name) VALUES(12,'Lohardaga');
INSERT INTO district(state,name) VALUES(12,'Pakaur');
INSERT INTO district(state,name) VALUES(12,'Palamu');
INSERT INTO district(state,name) VALUES(12,'Pashchimi Singhbhum');
INSERT INTO district(state,name) VALUES(12,'Purbi Singhbhum');
INSERT INTO district(state,name) VALUES(12,'Ramgarh');
INSERT INTO district(state,name) VALUES(12,'Ranchi');
INSERT INTO district(state,name) VALUES(12,'Sahebganj');
INSERT INTO district(state,name) VALUES(12,'Seraikela- Kharsawan');
INSERT INTO district(state,name) VALUES(12,'Simdega');
INSERT INTO district(state,name) VALUES(3,'Bagalkot');
INSERT INTO district(state,name) VALUES(3,'Bangalore Rural');
INSERT INTO district(state,name) VALUES(3,'Bangalore Urban');
INSERT INTO district(state,name) VALUES(3,'Belgaum');
INSERT INTO district(state,name) VALUES(3,'Bellary');
INSERT INTO district(state,name) VALUES(3,'Bidar');
INSERT INTO district(state,name) VALUES(3,'Bijapur');
INSERT INTO district(state,name) VALUES(3,'Chamrajnagar');
INSERT INTO district(state,name) VALUES(3,'Chikballapur');
INSERT INTO district(state,name) VALUES(3,'Chikmagalur');
INSERT INTO district(state,name) VALUES(3,'Chitradurga');
INSERT INTO district(state,name) VALUES(3,'Dakshina Kannada');
INSERT INTO district(state,name) VALUES(3,'Davangere');
INSERT INTO district(state,name) VALUES(3,'Dharwad');
INSERT INTO district(state,name) VALUES(3,'Gadag');
INSERT INTO district(state,name) VALUES(3,'Gulbarga');
INSERT INTO district(state,name) VALUES(3,'Hassan');
INSERT INTO district(state,name) VALUES(3,'Haveri');
INSERT INTO district(state,name) VALUES(3,'Kodagu');
INSERT INTO district(state,name) VALUES(3,'Kolar');
INSERT INTO district(state,name) VALUES(3,'Koppal');
INSERT INTO district(state,name) VALUES(3,'Mandya');
INSERT INTO district(state,name) VALUES(3,'Mysore');
INSERT INTO district(state,name) VALUES(3,'Raichur');
INSERT INTO district(state,name) VALUES(3,'Ramnagar');
INSERT INTO district(state,name) VALUES(3,'Shimoga');
INSERT INTO district(state,name) VALUES(3,'Tumkur');
INSERT INTO district(state,name) VALUES(3,'Udupi');
INSERT INTO district(state,name) VALUES(3,'Uttara Kannada');
INSERT INTO district(state,name) VALUES(3,'Yadgir');
INSERT INTO district(state,name) VALUES(26,'Alappuzha');
INSERT INTO district(state,name) VALUES(26,'Ernakulam');
INSERT INTO district(state,name) VALUES(26,'Idukki');
INSERT INTO district(state,name) VALUES(26,'Kannur');
INSERT INTO district(state,name) VALUES(26,'Kasaragod');
INSERT INTO district(state,name) VALUES(26,'Kollam');
INSERT INTO district(state,name) VALUES(26,'Kottayam');
INSERT INTO district(state,name) VALUES(26,'Kozhikode');
INSERT INTO district(state,name) VALUES(26,'Malappuram');
INSERT INTO district(state,name) VALUES(26,'Palakkad');
INSERT INTO district(state,name) VALUES(26,'Pathanamthitta');
INSERT INTO district(state,name) VALUES(26,'Thiruvananthapuram');
INSERT INTO district(state,name) VALUES(26,'Thrissur');
INSERT INTO district(state,name) VALUES(26,'Wayanad');
INSERT INTO district(state,name) VALUES(35,'Lakshadweep');
INSERT INTO district(state,name) VALUES(2,'Alirajpur');
INSERT INTO district(state,name) VALUES(2,'Anuppur');
INSERT INTO district(state,name) VALUES(2,'Ashoknagar');
INSERT INTO district(state,name) VALUES(2,'Balaghat');
INSERT INTO district(state,name) VALUES(2,'Barwani');
INSERT INTO district(state,name) VALUES(2,'Betul');
INSERT INTO district(state,name) VALUES(2,'Bhind');
INSERT INTO district(state,name) VALUES(2,'Bhopal');
INSERT INTO district(state,name) VALUES(2,'Burhanpur');
INSERT INTO district(state,name) VALUES(2,'Chhatarpur');
INSERT INTO district(state,name) VALUES(2,'Chhindwara');
INSERT INTO district(state,name) VALUES(2,'Damoh');
INSERT INTO district(state,name) VALUES(2,'Datia');
INSERT INTO district(state,name) VALUES(2,'Dewas');
INSERT INTO district(state,name) VALUES(2,'Dhar');
INSERT INTO district(state,name) VALUES(2,'Dindori');
INSERT INTO district(state,name) VALUES(2,'East Nimar( Khandwa)');
INSERT INTO district(state,name) VALUES(2,'Guna');
INSERT INTO district(state,name) VALUES(2,'Gwalior');
INSERT INTO district(state,name) VALUES(2,'Harda');
INSERT INTO district(state,name) VALUES(2,'Hoshangabad');
INSERT INTO district(state,name) VALUES(2,'Indore');
INSERT INTO district(state,name) VALUES(2,'Jabalpur');
INSERT INTO district(state,name) VALUES(2,'Jhabua');
INSERT INTO district(state,name) VALUES(2,'Katni');
INSERT INTO district(state,name) VALUES(2,'Mandla');
INSERT INTO district(state,name) VALUES(2,'Mandsaur');
INSERT INTO district(state,name) VALUES(2,'Morena');
INSERT INTO district(state,name) VALUES(2,'Narsimhapur');
INSERT INTO district(state,name) VALUES(2,'Neemuch');
INSERT INTO district(state,name) VALUES(2,'Panna');
INSERT INTO district(state,name) VALUES(2,'Raisen');
INSERT INTO district(state,name) VALUES(2,'Rajgarh');
INSERT INTO district(state,name) VALUES(2,'Ratlam');
INSERT INTO district(state,name) VALUES(2,'Rewa');
INSERT INTO district(state,name) VALUES(2,'Sagar');
INSERT INTO district(state,name) VALUES(2,'Satna');
INSERT INTO district(state,name) VALUES(2,'Sehore');
INSERT INTO district(state,name) VALUES(2,'Seoni');
INSERT INTO district(state,name) VALUES(2,'Shahdol');
INSERT INTO district(state,name) VALUES(2,'Shajapur');
INSERT INTO district(state,name) VALUES(2,'Sheopur');
INSERT INTO district(state,name) VALUES(2,'Shivpuri');
INSERT INTO district(state,name) VALUES(2,'Sidhi');
INSERT INTO district(state,name) VALUES(2,'Singrauli');
INSERT INTO district(state,name) VALUES(2,'Tikamgarh');
INSERT INTO district(state,name) VALUES(2,'Ujjain');
INSERT INTO district(state,name) VALUES(2,'Umaria');
INSERT INTO district(state,name) VALUES(2,'Vidisha');
INSERT INTO district(state,name) VALUES(2,'West Nimar (Khargone)');
INSERT INTO district(state,name) VALUES(1,'Solapur');
INSERT INTO district(state,name) VALUES(1,'Ahmadnagar');
INSERT INTO district(state,name) VALUES(1,'Akola');
INSERT INTO district(state,name) VALUES(1,'Amravati');
INSERT INTO district(state,name) VALUES(1,'Aurangabad');
INSERT INTO district(state,name) VALUES(1,'Bhandara');
INSERT INTO district(state,name) VALUES(1,'Bid');
INSERT INTO district(state,name) VALUES(1,'Buldana');
INSERT INTO district(state,name) VALUES(1,'Chandrapur');
INSERT INTO district(state,name) VALUES(1,'Dhule');
INSERT INTO district(state,name) VALUES(1,'Gadchiroli');
INSERT INTO district(state,name) VALUES(1,'Gondiya');
INSERT INTO district(state,name) VALUES(1,'Hingoli');
INSERT INTO district(state,name) VALUES(1,'Jalgaon');
INSERT INTO district(state,name) VALUES(1,'Jalna');
INSERT INTO district(state,name) VALUES(1,'Kolhapur');
INSERT INTO district(state,name) VALUES(1,'Latur');
INSERT INTO district(state,name) VALUES(1,'Mumbai');
INSERT INTO district(state,name) VALUES(1,'Mumbai (Suburban)');
INSERT INTO district(state,name) VALUES(1,'Nagpur');
INSERT INTO district(state,name) VALUES(1,'Nanded');
INSERT INTO district(state,name) VALUES(1,'Nandurbar');
INSERT INTO district(state,name) VALUES(1,'Nashik');
INSERT INTO district(state,name) VALUES(1,'Osmanabad');
INSERT INTO district(state,name) VALUES(1,'Parbhani');
INSERT INTO district(state,name) VALUES(1,'Pune');
INSERT INTO district(state,name) VALUES(1,'Raigarh');
INSERT INTO district(state,name) VALUES(1,'Ratnagiri');
INSERT INTO district(state,name) VALUES(1,'Sangli');
INSERT INTO district(state,name) VALUES(1,'Satara');
INSERT INTO district(state,name) VALUES(1,'Sindhudurg');
INSERT INTO district(state,name) VALUES(1,'Thane');
INSERT INTO district(state,name) VALUES(1,'Wardha');
INSERT INTO district(state,name) VALUES(1,'Washim');
INSERT INTO district(state,name) VALUES(1,'Yavatmal');
INSERT INTO district(state,name) VALUES(13,'Bishnupur');
INSERT INTO district(state,name) VALUES(13,'Chandel');
INSERT INTO district(state,name) VALUES(13,'Churachandpur');
INSERT INTO district(state,name) VALUES(13,'Imphal East');
INSERT INTO district(state,name) VALUES(13,'Imphal West');
INSERT INTO district(state,name) VALUES(13,'Senapati');
INSERT INTO district(state,name) VALUES(13,'Tamenglong');
INSERT INTO district(state,name) VALUES(13,'Thoubal');
INSERT INTO district(state,name) VALUES(13,'Ukhrul');
INSERT INTO district(state,name) VALUES(14,'East Garo Hills');
INSERT INTO district(state,name) VALUES(14,'East Khasi Hills');
INSERT INTO district(state,name) VALUES(14,'Jaintia Hills');
INSERT INTO district(state,name) VALUES(14,'Ri Bhoi');
INSERT INTO district(state,name) VALUES(14,'South Garo Hills');
INSERT INTO district(state,name) VALUES(14,'West Garo Hills');
INSERT INTO district(state,name) VALUES(14,'West Khasi Hills');
INSERT INTO district(state,name) VALUES(15,'Aizawl');
INSERT INTO district(state,name) VALUES(15,'Champhai');
INSERT INTO district(state,name) VALUES(15,'Kolasib');
INSERT INTO district(state,name) VALUES(15,'Lawngtlai');
INSERT INTO district(state,name) VALUES(15,'Lunglei');
INSERT INTO district(state,name) VALUES(15,'Mamit');
INSERT INTO district(state,name) VALUES(15,'Saiha');
INSERT INTO district(state,name) VALUES(15,'Serchhip');
INSERT INTO district(state,name) VALUES(16,'Dimapur');
INSERT INTO district(state,name) VALUES(16,'Kiphire');
INSERT INTO district(state,name) VALUES(16,'Kohima');
INSERT INTO district(state,name) VALUES(16,'Longleng');
INSERT INTO district(state,name) VALUES(16,'Mokokchung');
INSERT INTO district(state,name) VALUES(16,'Mon');
INSERT INTO district(state,name) VALUES(16,'Peren');
INSERT INTO district(state,name) VALUES(16,'Phek');
INSERT INTO district(state,name) VALUES(16,'Tuensang');
INSERT INTO district(state,name) VALUES(16,'Wokha');
INSERT INTO district(state,name) VALUES(16,'Zunheboto');
INSERT INTO district(state,name) VALUES(8,'Anugul');
INSERT INTO district(state,name) VALUES(8,'Balangir');
INSERT INTO district(state,name) VALUES(8,'Baleshwar');
INSERT INTO district(state,name) VALUES(8,'Bargarh');
INSERT INTO district(state,name) VALUES(8,'Baudh');
INSERT INTO district(state,name) VALUES(8,'Bhadrak');
INSERT INTO district(state,name) VALUES(8,'Cuttack');
INSERT INTO district(state,name) VALUES(8,'Debagarh');
INSERT INTO district(state,name) VALUES(8,'Dhenkanal');
INSERT INTO district(state,name) VALUES(8,'Gajapati');
INSERT INTO district(state,name) VALUES(8,'Ganjam');
INSERT INTO district(state,name) VALUES(8,'Jagatsinghapur');
INSERT INTO district(state,name) VALUES(8,'Jajapur');
INSERT INTO district(state,name) VALUES(8,'Jharsuguda');
INSERT INTO district(state,name) VALUES(8,'Kalahandi');
INSERT INTO district(state,name) VALUES(8,'Kandhamal');
INSERT INTO district(state,name) VALUES(8,'Kendrapara');
INSERT INTO district(state,name) VALUES(8,'Kendujhar (Keonjhar)');
INSERT INTO district(state,name) VALUES(8,'Khordha');
INSERT INTO district(state,name) VALUES(8,'Koraput');
INSERT INTO district(state,name) VALUES(8,'Malkangiri');
INSERT INTO district(state,name) VALUES(8,'Mayurbhanj');
INSERT INTO district(state,name) VALUES(8,'Nabarangapur');
INSERT INTO district(state,name) VALUES(8,'Nayagarh');
INSERT INTO district(state,name) VALUES(8,'Nuapada');
INSERT INTO district(state,name) VALUES(8,'Puri');
INSERT INTO district(state,name) VALUES(8,'Rayagada');
INSERT INTO district(state,name) VALUES(8,'Sambalpur');
INSERT INTO district(state,name) VALUES(8,'Sonapur');
INSERT INTO district(state,name) VALUES(8,'Sundargarh');
INSERT INTO district(state,name) VALUES(33,'Karaikal');
INSERT INTO district(state,name) VALUES(33,'Mahe');
INSERT INTO district(state,name) VALUES(33,'Pondicherry');
INSERT INTO district(state,name) VALUES(33,'Yanam');
INSERT INTO district(state,name) VALUES(21,'Ajitgarh(Mohali)');
INSERT INTO district(state,name) VALUES(21,'Amritsar');
INSERT INTO district(state,name) VALUES(21,'Barnala');
INSERT INTO district(state,name) VALUES(21,'Bathinda');
INSERT INTO district(state,name) VALUES(21,'Faridkot');
INSERT INTO district(state,name) VALUES(21,'Fatehgarh Sahib');
INSERT INTO district(state,name) VALUES(21,'Firozpur');
INSERT INTO district(state,name) VALUES(21,'Gurdaspur');
INSERT INTO district(state,name) VALUES(21,'Hoshiarpur');
INSERT INTO district(state,name) VALUES(21,'Jalandhar');
INSERT INTO district(state,name) VALUES(21,'Kapurthala');
INSERT INTO district(state,name) VALUES(21,'Ludhiana');
INSERT INTO district(state,name) VALUES(21,'Mansa');
INSERT INTO district(state,name) VALUES(21,'Moga');
INSERT INTO district(state,name) VALUES(21,'Muktsar');
INSERT INTO district(state,name) VALUES(21,'Patiala');
INSERT INTO district(state,name) VALUES(21,'Roopnagar');
INSERT INTO district(state,name) VALUES(21,'Sangrur');
INSERT INTO district(state,name) VALUES(21,'Shahid Bhagatpur');
INSERT INTO district(state,name) VALUES(21,'Tarn Taran');
INSERT INTO district(state,name) VALUES(6,'Ajmer');
INSERT INTO district(state,name) VALUES(6,'Alwar');
INSERT INTO district(state,name) VALUES(6,'Banswara');
INSERT INTO district(state,name) VALUES(6,'Baran');
INSERT INTO district(state,name) VALUES(6,'Barmer');
INSERT INTO district(state,name) VALUES(6,'Bharatpur');
INSERT INTO district(state,name) VALUES(6,'Bhilwara');
INSERT INTO district(state,name) VALUES(6,'Bikaner');
INSERT INTO district(state,name) VALUES(6,'Bundi');
INSERT INTO district(state,name) VALUES(6,'Chittaurgarh');
INSERT INTO district(state,name) VALUES(6,'Churu');
INSERT INTO district(state,name) VALUES(6,'Dausa');
INSERT INTO district(state,name) VALUES(6,'Dhaulpur');
INSERT INTO district(state,name) VALUES(6,'Dungarpur');
INSERT INTO district(state,name) VALUES(6,'Ganganagar');
INSERT INTO district(state,name) VALUES(6,'Hanumangarh');
INSERT INTO district(state,name) VALUES(6,'Jaipur');
INSERT INTO district(state,name) VALUES(6,'Jaisalmer');
INSERT INTO district(state,name) VALUES(6,'Jalor');
INSERT INTO district(state,name) VALUES(6,'Jhalawar');
INSERT INTO district(state,name) VALUES(6,'Jhunjhunun');
INSERT INTO district(state,name) VALUES(6,'Jodhpur');
INSERT INTO district(state,name) VALUES(6,'Karauli');
INSERT INTO district(state,name) VALUES(6,'Kota');
INSERT INTO district(state,name) VALUES(6,'Nagaur');
INSERT INTO district(state,name) VALUES(6,'Pali');
INSERT INTO district(state,name) VALUES(6,'Pratapgarh');
INSERT INTO district(state,name) VALUES(6,'Rajsamand');
INSERT INTO district(state,name) VALUES(6,'Sawai Madhopur');
INSERT INTO district(state,name) VALUES(6,'Sikar');
INSERT INTO district(state,name) VALUES(6,'Sirohi');
INSERT INTO district(state,name) VALUES(6,'Tonk');
INSERT INTO district(state,name) VALUES(6,'Udaipur');
INSERT INTO district(state,name) VALUES(20,'East Sikkim');
INSERT INTO district(state,name) VALUES(20,'North Sikkim');
INSERT INTO district(state,name) VALUES(20,'South Sikkim');
INSERT INTO district(state,name) VALUES(20,'West Sikkim');
INSERT INTO district(state,name) VALUES(27,'Ariyalur');
INSERT INTO district(state,name) VALUES(27,'Chennai');
INSERT INTO district(state,name) VALUES(27,'Coimbatore');
INSERT INTO district(state,name) VALUES(27,'Cuddalore');
INSERT INTO district(state,name) VALUES(27,'Dharmapuri');
INSERT INTO district(state,name) VALUES(27,'Dindigul');
INSERT INTO district(state,name) VALUES(27,'Erode');
INSERT INTO district(state,name) VALUES(27,'Kancheepuram');
INSERT INTO district(state,name) VALUES(27,'Kanniyakumari');
INSERT INTO district(state,name) VALUES(27,'Karur');
INSERT INTO district(state,name) VALUES(27,'Krishnagiri');
INSERT INTO district(state,name) VALUES(27,'Madurai');
INSERT INTO district(state,name) VALUES(27,'Nagapattinam');
INSERT INTO district(state,name) VALUES(27,'Namakkal');
INSERT INTO district(state,name) VALUES(27,'Perambalur');
INSERT INTO district(state,name) VALUES(27,'Pudukkottai');
INSERT INTO district(state,name) VALUES(27,'Ramanathapuram');
INSERT INTO district(state,name) VALUES(27,'Salem');
INSERT INTO district(state,name) VALUES(27,'Sivaganga');
INSERT INTO district(state,name) VALUES(27,'Thanjavur');
INSERT INTO district(state,name) VALUES(27,'The Nilgiris');
INSERT INTO district(state,name) VALUES(27,'Theni');
INSERT INTO district(state,name) VALUES(27,'Thirupur');
INSERT INTO district(state,name) VALUES(27,'Thiruvallur');
INSERT INTO district(state,name) VALUES(27,'Thiruvarur');
INSERT INTO district(state,name) VALUES(27,'Thoothukkudi');
INSERT INTO district(state,name) VALUES(27,'Tiruchirappalli');
INSERT INTO district(state,name) VALUES(27,'Tirunelveli');
INSERT INTO district(state,name) VALUES(27,'Tiruvannamalai');
INSERT INTO district(state,name) VALUES(27,'Vellore');
INSERT INTO district(state,name) VALUES(27,'Viluppuram');
INSERT INTO district(state,name) VALUES(27,'Virudhunagar');
INSERT INTO district(state,name) VALUES(25,'Dhalai');
INSERT INTO district(state,name) VALUES(25,'North Tripura');
INSERT INTO district(state,name) VALUES(25,'South Tripura (Gomati)');
INSERT INTO district(state,name) VALUES(25,'West Tripura');
INSERT INTO district(state,name) VALUES(7,'Agra');
INSERT INTO district(state,name) VALUES(7,'Aligarh');
INSERT INTO district(state,name) VALUES(7,'Allahabad');
INSERT INTO district(state,name) VALUES(7,'Ambedkar Nagar');
INSERT INTO district(state,name) VALUES(7,'Auraiya');
INSERT INTO district(state,name) VALUES(7,'Azamgarh');
INSERT INTO district(state,name) VALUES(7,'Badaun');
INSERT INTO district(state,name) VALUES(7,'Baghpat');
INSERT INTO district(state,name) VALUES(7,'Bahraich');
INSERT INTO district(state,name) VALUES(7,'Ballia');
INSERT INTO district(state,name) VALUES(7,'Balrampur');
INSERT INTO district(state,name) VALUES(7,'Banda');
INSERT INTO district(state,name) VALUES(7,'Barabanki');
INSERT INTO district(state,name) VALUES(7,'Bareilly');
INSERT INTO district(state,name) VALUES(7,'Basti');
INSERT INTO district(state,name) VALUES(7,'Bijnor');
INSERT INTO district(state,name) VALUES(7,'Bulandshahr');
INSERT INTO district(state,name) VALUES(7,'Chandauli');
INSERT INTO district(state,name) VALUES(7,'Chitrakoot');
INSERT INTO district(state,name) VALUES(7,'Deoria');
INSERT INTO district(state,name) VALUES(7,'Etah');
INSERT INTO district(state,name) VALUES(7,'Etawah');
INSERT INTO district(state,name) VALUES(7,'Faizabad');
INSERT INTO district(state,name) VALUES(7,'Farrukhabad');
INSERT INTO district(state,name) VALUES(7,'Fatehpur');
INSERT INTO district(state,name) VALUES(7,'Firozabad');
INSERT INTO district(state,name) VALUES(7,'Gautam Buddha Nagar');
INSERT INTO district(state,name) VALUES(7,'Ghaziabad');
INSERT INTO district(state,name) VALUES(7,'Ghazipur');
INSERT INTO district(state,name) VALUES(7,'Gonda');
INSERT INTO district(state,name) VALUES(7,'Gorakhpur');
INSERT INTO district(state,name) VALUES(7,'Hamirpur');
INSERT INTO district(state,name) VALUES(7,'Hardoi');
INSERT INTO district(state,name) VALUES(7,'Hathras');
INSERT INTO district(state,name) VALUES(7,'Jalaun');
INSERT INTO district(state,name) VALUES(7,'Jaunpur');
INSERT INTO district(state,name) VALUES(7,'Jhansi');
INSERT INTO district(state,name) VALUES(7,'Jyotiba Phule Nagar');
INSERT INTO district(state,name) VALUES(7,'Kannauj');
INSERT INTO district(state,name) VALUES(7,'Kanpur Dehat');
INSERT INTO district(state,name) VALUES(7,'Kanpur Nagar');
INSERT INTO district(state,name) VALUES(7,'Kanshiram Nagar');
INSERT INTO district(state,name) VALUES(7,'Kaushambi');
INSERT INTO district(state,name) VALUES(7,'Kheri (Lakhimpur)');
INSERT INTO district(state,name) VALUES(7,'Kushinagar');
INSERT INTO district(state,name) VALUES(7,'Lalitpur');
INSERT INTO district(state,name) VALUES(7,'Lucknow');
INSERT INTO district(state,name) VALUES(7,'Maharajganj');
INSERT INTO district(state,name) VALUES(7,'Mahoba');
INSERT INTO district(state,name) VALUES(7,'Mainpuri');
INSERT INTO district(state,name) VALUES(7,'Mathura');
INSERT INTO district(state,name) VALUES(7,'Mau');
INSERT INTO district(state,name) VALUES(7,'Meerut');
INSERT INTO district(state,name) VALUES(7,'Mirzapur');
INSERT INTO district(state,name) VALUES(7,'Moradabad');
INSERT INTO district(state,name) VALUES(7,'Muzaffarnagar');
INSERT INTO district(state,name) VALUES(7,'Pilibhit');
INSERT INTO district(state,name) VALUES(7,'Pratapgarh');
INSERT INTO district(state,name) VALUES(7,'Rae Bareli');
INSERT INTO district(state,name) VALUES(7,'Rampur');
INSERT INTO district(state,name) VALUES(7,'Saharanpur');
INSERT INTO district(state,name) VALUES(7,'Sant Kabir Nagar');
INSERT INTO district(state,name) VALUES(7,'Sant Ravidas Nagar');
INSERT INTO district(state,name) VALUES(7,'Shahjahanpur');
INSERT INTO district(state,name) VALUES(7,'Shrawasti');
INSERT INTO district(state,name) VALUES(7,'Siddharthnagar');
INSERT INTO district(state,name) VALUES(7,'Sitapur');
INSERT INTO district(state,name) VALUES(7,'Sonbhadra');
INSERT INTO district(state,name) VALUES(7,'Sultanpur');
INSERT INTO district(state,name) VALUES(7,'Unnao');
INSERT INTO district(state,name) VALUES(7,'Varanasi');
INSERT INTO district(state,name) VALUES(11,'Almora');
INSERT INTO district(state,name) VALUES(11,'Bageshwar');
INSERT INTO district(state,name) VALUES(11,'Chamoli');
INSERT INTO district(state,name) VALUES(11,'Champawat');
INSERT INTO district(state,name) VALUES(11,'Dehradun');
INSERT INTO district(state,name) VALUES(11,'Garhwal');
INSERT INTO district(state,name) VALUES(11,'Hardwar');
INSERT INTO district(state,name) VALUES(11,'Nainital');
INSERT INTO district(state,name) VALUES(11,'Pithoragarh');
INSERT INTO district(state,name) VALUES(11,'Rudraprayag');
INSERT INTO district(state,name) VALUES(11,'Tehri Garhwal');
INSERT INTO district(state,name) VALUES(11,'Udham Singh Nagar');
INSERT INTO district(state,name) VALUES(11,'Uttarkashi');
INSERT INTO district(state,name) VALUES(10,'Bankura');
INSERT INTO district(state,name) VALUES(10,'Barddhaman');
INSERT INTO district(state,name) VALUES(10,'Birbhum');
INSERT INTO district(state,name) VALUES(10,'Dakshin Dinajpur');
INSERT INTO district(state,name) VALUES(10,'Darjiling');
INSERT INTO district(state,name) VALUES(10,'East Medinipur');
INSERT INTO district(state,name) VALUES(10,'Haora');
INSERT INTO district(state,name) VALUES(10,'Hugli');
INSERT INTO district(state,name) VALUES(10,'Jalpaiguri');
INSERT INTO district(state,name) VALUES(10,'Koch Bihar');
INSERT INTO district(state,name) VALUES(10,'Kolkata');
INSERT INTO district(state,name) VALUES(10,'Maldah');
INSERT INTO district(state,name) VALUES(10,'Murshidabad');
INSERT INTO district(state,name) VALUES(10,'Nadia');
INSERT INTO district(state,name) VALUES(10,'North Twenty Four Pargana');
INSERT INTO district(state,name) VALUES(10,'Puruliya');
INSERT INTO district(state,name) VALUES(10,'South Twenty Four Pargana');
INSERT INTO district(state,name) VALUES(10,'Uttar Dinajpur');
INSERT INTO district(state,name) VALUES(10,'West Medinipur');
